apiVersion: apps/v1
kind: Deployment
metadata:
  name: otusapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otusapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: otusapp
    spec:
      containers:
        - name: otusapp
          image: "evilsnow/otus:2.0.0"
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: dbUrl
                  name: otusapp-cm
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  key: dbUser
                  name: otusapp-secrets
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbPassword
                  name: otusapp-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 5
